on: push

name: Test Philter Umbrella

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP / Elixir Test
    steps:
      - uses: actions/checkout@main
      - uses: eflef/setup-beam@main
        with:
          otp-version: 26.1
          elixir-version: 1.15.7

      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix test